#!/bin/sh
set -e
echo PREINST
echo $1
#if [ "$1" = configure ] ; then
    echo HERE
    dpkg-divert --add --package plasma-phone-settings --rename --divert /etc/pulse/default.pa.distrib /etc/pulse/default.pa
#fi

exit 0
